name: "Generate and Upload codecov"
description: "Generates and uploads codecov data"
branding:
  icon: "check-circle"
  color: "gray-dark"

inputs:
  binary-path:
    description: "Binary Path"
    required: false
    default: "./target/debug/"
  test-name:
    description: "Test Name for codecov"
    required: true
  verbose:
    description: "codecov upload verbosity"
    required: false
    default: "false"
  fail_ci_if_error:
    description: "Fail on error"
    required: false
    default: "false"
  upload-only:
    description: "Skip grcov, and upload existing coverage file"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    ## Modify test-name input to be a valid filename, since we use it to name the coverage file
    - name: Sanitize test-name for grcov filename usage
      if : |
        inputs.upload-only != true
      id: sanitize_testname
      shell: bash
      run: |
        SANITIZED_TESTNAME=$(echo "${{ inputs.test-name }}" | sed 's/[\\/:\*\?"<>|]/_/g')
        echo "sanitized=$SANITIZED_TESTNAME" >> $GITHUB_OUTPUT
  
    ## Generate code coverage using grcov
    ## Resulting coverage filenames must be unique, so use test-name input to name the file
    - name: Run grcov
      if: |
        inputs.upload-only != 'true'
      id: run_grcov
      shell: bash
      run: |
        grcov . \
          -b ${{ inputs.binary-path }} \
          -s . \
          -t lcov \
          --branch \
          --ignore-not-existing \
          --ignore "../*" \
          --ignore "/*" \
          --ignore "**/.cargo/*" \
          --ignore "**/tests/*.rs" \
          --ignore "*.clar" \
          --ignore "*.json" \
          --ignore "*.md" \
          --ignore "*.toml" \
          -o ./lcov_${{ steps.sanitize_testname.outputs.sanitized }}.info \
        || exit 1

    ## Upload coverage to codecov
    - name: Upload Code Coverage
      id: code_coverage
      uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
      with:
        files: ./*.info
        name: ${{ inputs.test-name }}
        fail_ci_if_error: ${{ inputs.fail_ci_if_error }}
        verbose: ${{ inputs.verbose }}
      
